### ISSUE TITLE
保有ポイントがマイナスの場合の利用可能ポイント表示

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/point-plugin#125]
## 現象

**現在の保有ポイントは「0 pt」です。「-1,000 pt」までご利用いただけます。** と表示されてしまう。
#107 のデグレーション
## 再現手順

ユニットテストにて再現。 保有ポイントをマイナスにすることで再現
## 期待値

**現在の保有ポイントは「0 pt」です。** と表示する

**Comment by chihiro-adachi** [comment]
#127 で対応
