### ISSUE TITLE
受注を保存出来ません。

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/point-plugin#135]
## 現象

受注を保存出来ません。いつも保有ポイントのバリデーションを聞かれています。
## 再現手順

1．ユーザの1000ポイントで設定する。
2．すべて1000ポイントを利用する。
3．受注編集画面にステータス変更して保存する。
　=>`保有ポイント以内で入力してください`というバリデーションを出ています。保存出来ない（ＮＧ）
## 期待値

バリデーションを聞かないで、保存できるように。

**Comment by chihiro-adachi** [comment]
#139 で対応
