### ISSUE TITLE
保有ポイントマイナス通知メールの文面

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/point-plugin#136]
## 現象

以下のようなメールが送信される

```
会員ID：4156
○ ○ 様の保有ポイントがマイナスになっています。

注文番号：10443

利用ポイント：-100

所持ポイント：-1,100

```
## 再現手順

ユニットテストにて再現。
ポイント利用後に、会員の保有ポイントをマイナス値とすることで再現
## 期待値
- 利用ポイントは正の整数で表示するのが正しい
- 所持ポイントではなく、「保有」ポイントが正しい

**Comment by chihiro-adachi** [comment]
#137 で対応
