### ISSUE TITLE
【管理画面】会員編集画面にてポイント変更するとパスワードが*****になる

### ISSUE THREAD

**Issue by hiroo2016** [EC-CUBE/point-plugin#143]
## 現象

管理画面の会員編集画面でポイントを変更すると、パスワードが********に更新されてしまう
## 再現手順

１、管理画面にて任意の会員の詳細画面へ
２、ポイント数を変更して登録
## 期待値

dtb_customer.passwordは更新されない
## 環境
- OS：OS X El Capitan
- Database：mysql5.7
- WebServer：apache2.4
- PHP version：7.0
- EC-CUBE vesrsion：3.0.10

**Comment by chihiro-adachi** [comment]
@hiroo2016 
こちら手元の環境で試しましたが、再現しませんでした。
インストールされているプラグインは、ポイントプラグインのみでしょうか？

**Comment by ryo-endo** [comment]
こちらが原因かも。ご参照ください。
https://github.com/EC-CUBE/mail-magazine-plugin/issues/17

**Comment by hiroo2016** [comment]
@chihiro-adachi @ryo-endo 
メルマガプラグインもインストールされていました。
ryo-endoさんのおっしゃる通り、メルマガプラグインが原因でした。
確認不足ですみません。
お手数おかけしました。

**Comment by ryo-endo** [comment]
いえいえ。こちらこそメルマガプラグインでご不便おかけしました。
ご報告ありがとうございました。
