### ISSUE TITLE
メール一斉通知した場合、加算ポイントがメール本文に表示されない

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/point-plugin#32]
一斉通知したときにメール本文の加算ポイントが表示されない。
個別でメール送信した場合、加算ポイントは表示されている。

**Comment by geany-y** [comment]
[ 前提 ]
以下メールで確認
受注管理 > メール一括 > 「ご注文情報の確認」

[ 操作 ]
①ポイント機能がONの状態で、新規ユーザーを3ユーザー作成し、それぞれでログイン後、商品を購入
その後、受注管理で検索後、一斉送信
②①と購入は同条件で、メール送信の際のみ、個別送信で送信

[ 結果 ]
「操作」①②においてメール内にポイント欄確認出来ず。
※送信前の確認画面では表示されている。

**Comment by chihiro-adachi** [comment]
#138 で対応
