### ISSUE TITLE
保有ポイントが更新されない

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/point-plugin#34]
[ 対象テスト ]
結合: フォームバリデーションテスト

[ テスト番号 ]
PLGP0002-FV01-S83
PLGP0002-FV01-S84

[ テスト内容 ]
PLGP0002-FV01-S83
使用ポイントの設定画面: ポイント利用項目欄に以下入力し「登録する」ボタンを押下する
ご注文内容確認画面に遷移
・保有ポイント最大値以下の値""画面下部のポイント利用欄の保有ポイントが「利用ポイント」分減算されている

PLGP0002-FV01-S84
使用ポイントの設定画面: ポイント利用項目欄に以下入力し「登録する」ボタンを押下する
ご注文内容確認画面に遷移
・保有ポイント最大値以下の値「注文する」ボタン上部、項目「合計」の上の今回利用ポイントが入力した利用ポイント分表示されている
合計金額は「ポイント機能管理/ポイント換算率」にもとづいた値が差し引かれて表示されている
ポイント情報の上に、「値引き」欄が表示され、設定された値にもとづき計算した金額が負の値で表示されている

[ 結果 ]
・保有ポイントに変化なし
・plg_pointには利用ポイントデーターあり
・plg_point_customerでは利用ポイントが反映されていない、保有ポイントデータあり
・注文完了後には、「保有ポイントは更新」

[ 備考 ]
使用ポイント画面で、ポイントを使用した後、ご注文情報の確認画面に遷移、
その後再び、使用ポイント確認画面に遷移し、保有ポイントを確認したが、保有ポイントに
使用ポイント減算は反映されず

[ 環境 ]
Vagrant
PHP: 5.4.45
PostgreSQL : 8.4.20
IE11

**Comment by chihiro-adachi** [comment]
購入確認画面およびポイント利用画面の保有ポイント表示の増減や、対象の購入金額の表示の増減は行いません。データベース内の数値に異常がなければOKです。
