### ISSUE TITLE
未参照の変数

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/point-plugin#37]
`$lastPreUsePoint` は、どこからも参照されていない

https://github.com/EC-CUBE/point-plugin/blob/d435b7a01f22f14ab53c3881da7e34fcc1f10ead/Helper/PointCalculateHelper/PointCalculateHelper.php#L599

**Comment by chihiro-adachi** [comment]
$usePointで判定する、が正しい

**Comment by nanasess** [comment]
- `$lastPreUsePoint` の後続の処理を動くようにすると、 PostgreSQL で DB エラーとなる
- そもそも該当の処理は不要と思われる

上記の理由で、該当の処理を削除しました(#51)
