### ISSUE TITLE
PointCalculateHelper の例外

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/point-plugin#38]
`PointCalculateHelper` で 以下の例外をスローしている箇所がある
- `Symfony\Component\Form\Exception\LogicException`
- `Doctrine\ORM\EntityNotFoundException`

これらは、それぞれ SymfonyFormComponent, DoctrineORM の例外なので、ここでスローすべきではない

[\LogicException](http://php.net/manual/ja/class.logicexception.php) で良いと思われる

**Comment by chihiro-adachi** [comment]
#50 で対応
