### ISSUE TITLE
ポイントを使用すると加算ポイントが０になる

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/point-plugin#39]
## 現象

ポイントを使用すると加算ポイントが０になる
## 再現手順

ポイント設定＝ポイント利用時に減算
購入確認画面で、利用ポイントを設定後に、加算ポイントを確認。
## 期待値

減算した上で、適切なポイントが加算されること。

**Comment by chihiro-adachi** [comment]
基本ポイント付与率の計算に誤りがある

https://github.com/EC-CUBE/point-plugin/blob/master/Helper/PointCalculateHelper/PointCalculateHelper.php#L453

・誤：$basicRate = ($this->basicRate / 100) + 1;
・正：$basicRate = ($this->basicRate / 100) ;

参照：
https://github.com/EC-CUBE/ec-cube/issues/1233#issuecomment-161178023
http://svn.ec-cube.net/open_trac/ticket/1796

**Comment by chihiro-adachi** [comment]
#60 で修正
