### ISSUE TITLE
値引きをしても、値引き前の金額に対してポイント加算される

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/point-plugin#40]
## 現象

ポイントプラグイン以外で値引きをしても、
値引き前の金額から計算したポイントが加算されます。
## 再現手順

1.商品追加>カゴ>注文内容確認の画面に遷移。
2.`dtb_order`に作成されたレコードの`discount`に値引き値を入力。
3.`支払方法`を変更して、加算ポイントの再計算を行う。
　⇒ 加算ポイントが変化しない。値引き前の金額から計算したポイントのまま(NG)

**Comment by chihiro-adachi** [comment]
加算ポイントの計算は、以下の計算式で行います。
https://github.com/EC-CUBE/ec-cube/issues/1233#issuecomment-161178023

```
基本の計算式
　商品ごとに設定されているポイント付与率に応じて付与する
　　販売価格＊（基本ポイント付与率 or 商品ごとのポイント付与率） ＝ 商品の付与ポイント（A）
　　（A）*購入数 ＝ 明細付与ポイント（B)
　（B1）+（B2)+...(Bn) = 合計付与ポイント（P)

ポイント利用時に減算する場合の減算式

ポイント値引き額に相当するポイントを合計付与ポイントから減算する

　　利用ポイント数 ＊ ポイント金額換算率 ＝ ポイント値引額 （X）
(P)- （X)*基本ポイント付与率 = 合計付与ポイント（P')
```

加算ポイントの減算方法としてはポイントを利用した際の減算のみ行うものし、他のプラグインも扱うことが想定されるdiscountは考慮しないものとします。
