### ISSUE TITLE
マイページにポイントをマイナスに表示しています。

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/point-plugin#42]
## 現象　

受注を削除すると、ポイントはマイナスになります。
## 再現手順

1.受注マスター>受注一覧
2.受注を選択して、削除します。
3．通知メールを飛んできます。
  =>マイページをアクセスして、ポイントはマイナスを表示してしまいました（ＮＧ）

**Comment by chihiro-adachi** [comment]
#61 で修正.
