### ISSUE TITLE
別々のブラウザから保持しているポイントを全て利用して商品を購入してもポイントが利用できる

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/point-plugin#43]
## 現象

PLGP0001-GEF01-S16
別々のブラウザから保持しているポイントを全て利用して商品を購入してもポイントが利用できてしまう。
## 再現手順

別々のブラウザで商品購入時にポイントを利用して購入するとポイント利用可能
## 期待値

どちらかのブラウザではポイント利用できないようエラーにする

**Comment by nanasess** [comment]
排他制御の懸念あり
参考 https://github.com/EC-CUBE/ec-cube/issues/1544

**Comment by nanasess** [comment]
ポイントを利用する前に、現在ポイントのマイナス評価をしているのが原因(保有ポイントを減算する前なので、マイナスにならない)
https://github.com/EC-CUBE/point-plugin/blob/e3bbbd5811471cdbcc3da83ad9258b207723e086/Event/WorkPlace/FrontShoppingComplete.php#L102

また、マイナスになった場合、管理者にメール送信するのみなので、購入は完了してしまう。
ここではメール送信しなくても良いので、エラーにして購入完了を止めるべき。

**Comment by chihiro-adachi** [comment]
本来は購入完了を停止するが望ましいが、本体側に適切なフックポイントがなく、制御することができない。

以下の機能を提供することにより、管理者が対処できるように対応を行う
- 管理者に対し、マイナスが発生した場合のアラートメールを送信する
- マイナスが発生した受注の場合、受注編集画面でアラートを表示する
- 購入完了時、マイナスが発生する場合は、注文完了画面にアラートを表示する

対応PR
https://github.com/EC-CUBE/point-plugin/pull/68
