### ISSUE TITLE
購入時のメール本文に利用ポイントが表示されていない

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/point-plugin#45]
## 現象
- [x] 購入時のメール本文に利用ポイントが表示されていない
- [x] 画面上では「使用ポイント」となっているが「利用ポイント」に表記を統一
- [x] 利用ポイントの設定画面のボダンラベルを「登録する」から「ポイントを利用する」に変更

**Comment by chihiro-adachi** [comment]
#54 で修正
