### ISSUE TITLE
受注の商品追加

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/point-plugin#48]
## 現象

受注登録にすべて商品を削除して、新しい商品を追加するとこの商品の表示する情報はおかしくなります。
## 再現手順

1．受注登録を遷移する
2．何か商品を追加する。
3．すべての商品を削除する。
4．また、商品を追加して>ディナーフォークを決定
　=>決定したディナーフォークですが、ディナーフォークの情報に表示する（ＮＧ）
## 期待値

ディナーフォークの情報を表示する。

**Comment by chihiro-adachi** [comment]
本体の不具合、発生頻度は低いと思われる
