### ISSUE TITLE
PointCalculateHelper::usePoint がマイナスになるケースの扱い

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/point-plugin#49]
PointCalculateHelper::usePoint は、マイナスになる可能性が考慮されていないと思われる。
#31 でマイナスの値がセットされている

**Comment by nanasess** [comment]
マイナスになった場合、以下のメソッドは正しく動作しないと思われる
- `PointCalculateHelper::setDiscount()`
- `PointCalculateHelper::getConversionPoint()`

**Comment by chihiro-adachi** [comment]
#55 で修正
