### ISSUE TITLE
受注管理画面(新規登録)をクリックすると「利用ポイント・加算ポイント」のテキストボックスが表示されている

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/point-plugin#64]
## 現象

再現手順を行うと「お届け情報・お届け日」の下に「利用ポイント・加算ポイント」のテキストボックスが表示されている
## 再現手順

①ポイントプラグインをインストール・有効
②管理画面メニューから「受注管理 > 受注登録」をクリック
## 期待値

①表示しない
②表示するなら本来の箇所(受注商品情報の合計の上)に表示する
※上記のいずれか( 元来は①採用 )

**Comment by chihiro-adachi** [comment]
①表示しない、が正
