### ISSUE TITLE
受注管理受注登録時に「ポイント確定ステータス : 確定/非確定」でログレコードを作成するかどうか

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/point-plugin#65]
## 現象

1.) 受注ステータスを「非確定」で、「利用ポイント・保有ポイント」を空欄で登録すると、以下の結果となる
[ テーブルレコード ]
・plg_point : レコードなし
・plg_point_status: レコードなし

2.) 受注ステータスを「確定」で、「利用ポイント・保有ポイント」を空欄で登録すると、以下の結果となる
[ テーブルレコード ]
・plg_point : レコードなし
・plg_point_status: レコードあり
## 再現手順

①管理画面 > 受注登録に遷移
②会員情報・商品情報のみを入力し、「受注情報を登録」を押下
③テーブル「plg_point」「plg_point_type」を確認
## 期待値

①「ログ」の考え方を活かすなら全て登録
②「ログ」の考え方を活かさなくても「plg_point_status」には「受注ステータス」が「確定・非確定」にかかわらずレコードを作成する
※上記いずれか

**Comment by chihiro-adachi** [comment]
①のレコードを作成する、で統一

**Comment by chihiro-adachi** [comment]
#130 で対応
