### ISSUE TITLE
ポイントプラグインを一度削除した後、再インストール時に有効化でエラー

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/point-plugin#66]
## 現象

ポイントプラグインの削除を一度でも行うと以下エラーで有効化できず
![image](https://cloud.githubusercontent.com/assets/14922838/15244823/0ea4c868-193e-11e6-8170-c571ac62ba5b.png)
## 再現手順

①ポイントプラグインをインストール
②有効化
③ポイント機能を何かしら利用
④無効化
⑤削除
⑥再度インストール
⑦有効化
⑧前述エラー
※EC-CUBEの再インストールでも同様
## 期待値

通常に有効化される
## 備考

Postgresのシーケンスが残っているのが原因と思われる
![image](https://cloud.githubusercontent.com/assets/14922838/15245032/332d4af6-193f-11e6-9cd4-73e630866a9d.png)

**Comment by chihiro-adachi** [comment]
以下で修正済
https://github.com/EC-CUBE/point-plugin/commit/53d6c17b0136b38e95d50d1181ea90b87fa90799
