### ISSUE TITLE
RememberMeでの挙動

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/point-plugin#73]
## 現象

①「次回から自動的にログインする」の設定でログイン後、ブラウザから、マイページなどにアクセス
すると、ポイント機能プラグインの挙動が非会員と同様の挙動となる
## 再現手順

①設定  > 基本情報設定 > ショップマスター > 会員設定 > 自動ログイン機能を有効にする 
上記を有効にする
②フロントページのログイン画面に移動する
「次回から自動的にログインする」の左にあるチェックにチェックをつけログイン
③マイページでポイント情報が表示されている事を確認
④ブラウザを閉じる
⑤再度同一ブラウザを立ち上げ、mypageのurlを入力する。
→ポイント関連情報が表示されない
## 期待値

①自動ログイン時もポイント機能ログイン済み会員と同じ挙動で使えること

**Comment by chihiro-adachi** [comment]
フロント側での権限チェックは以下の3種
- IS_AUTHENTICATED_REMEMBERED
  - remenber meでログイン済みの状態の時にtrue
- IS_AUTHENTICATED_FULLY
  - ログインフォームからログインした状態の時にtrue
- ROLE_USER
  - 上記どちらでもtrue

基本的には本体の権限チェックがきいた上でイベントが実行されるため、ROLE_USERでチェックすること

**Comment by chihiro-adachi** [comment]
#99 で対応
