### ISSUE TITLE
ポイント上限に達すると、会員情報の編集ができなくなってしまう

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/point-plugin#75]
## 現象

ポイント上限に達すると、会員情報の編集ができなくなってしまう
## 再現手順
1. 会員の保有ポイントを 100000 に設定
2. 商品を購入
3. 商品ステータスを、確定ステータスに変更
4. 会員情報を変更しようとすると「100000以下でなければなりません。」というエラーになる
## 期待値

ポイントを変更した結果、上限を越えた場合にエラーにすべき。

**Comment by chihiro-adachi** [comment]
intの上限で設定する(~~8桁~~9桁を上限とする)
