### ISSUE TITLE
受注編集で、利用ポイントが反映されない？

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/point-plugin#76]
## 現象

お支払い合計よりも、利用ポイントが多い場合、利用ポイントが反映されない？
## 再現手順
1. 会員の保有ポイントを 102200pt に設定する(100000pt に設定したあと、 2200pt 分の商品を購入する)
2. ディナーフォーク( 材質： プラチナ / サイズ： 150cm )  をポイント使用せず購入する
3. 受注編集で、ディナーフォークの価格を199円に設定し「計算結果の確認」をクリックする
4. 利用ポイントを 100000pt に設定する
5. 「受注情報を登録する」をクリックする
6. お支払い金額「1,215円」になってしまう(商品215円 + 送料1000円) 会員の保有ポイントは 2200pt になってしまう
## 期待値

「利用ポイントは 1,215pt 以内で入力してください」といったエラーメッセージを表示すべき

**Comment by chihiro-adachi** [comment]
受注編集時は、金額計算等の自動連動は行わない
ユーザビリティの観点から、注意書きやメッセージは必要

**Comment by chihiro-adachi** [comment]
#131 で対応
