### ISSUE TITLE
Order::discount に負の整数を設定した場合、利用ポイントが記録されない

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/point-plugin#80]
## 現象

Order::discount に負の整数を設定した場合、利用ポイントが記録されない
## 再現手順

ユニットテストで再現
https://github.com/nanasess/point-plugin/commit/09622896508843728c19fb3f685890c208a49db2
## 期待値

Order::discount に負の整数を設定しても、正しく利用ポイントが記録される

**Comment by chihiro-adachi** [comment]
0以上であれば登録する、というチェックをかけているが、不要な制御ではないかと思われる。

**Comment by chihiro-adachi** [comment]
#89 で修正
