### ISSUE TITLE
受注で発生した加算ポイントをそのまま利用して注文できてしまう

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/point-plugin#81]
## 現象

受注で発生した加算ポイントを、その同一受注ですぐに使用して注文できてしまいます。
（ポイントがマイナスになった検知もされない）
## 再現手順

(前提条件)
ポイントの加算タイミングは「新規受注」
（手順）
1.会員情報編集で、保有ポイントを100ptにしておく。
2.ブラウザAでパーコレータを1個カゴに入れて購入へ。
　ポイント100pt使用して、[注文する]ボタンの直前の状態にしておく。
3.ブラウザBでパーコレータを**5個**カゴに入れて購入へ。
　ポイント100pt使用して、[注文する]ボタンの直前の状態にしておく。
4.ブラウザAで、[注文する]ボタンを押下。
　⇒正常に受注確定(OK)
　⇒このとき残ポイントは、100pt + 28pt（加算）- 100pt(利用) = 28pt 。
5.ブラウザBで、[注文する]ボタンを押下。
　⇒正常に受注確定（NG）
　⇒このとき残ポイントは、
　　28pt + 140pt（加算） - 100pt(利用) = 68pt となってしまっているため、
　　マイナスを検知できていない。
## 期待値

加算ポイントは、次の受注以降でしか使用できないこと。

**Comment by ryo-endo** [comment]
処理の順番を変更します。

```
利用ポイントの減算→取得ポイントの加算→保有ポイントマイナスチェック
```

↓

```
利用ポイントの減算→保有ポイントマイナスチェック→取得ポイントの加算
```

**Comment by lammn** [comment]
以上の5（ブラウザB）先にやったら、両方のブラウザは正常に受注確定になってしまいました。（ＮＧ）
エラーにならいないです。

**Comment by chihiro-adachi** [comment]
手順5(ブラウザB)を先に実行したときの挙動としては、

Bの結果：100pt - 100pt(利用) + 140pt(加算) = 140pt
Aの結果：140pt - 100pt(利用) + 28pt = 68pt

となり、保有ポイントは正の値になるため、両方正常に注文は完了されます。
