### ISSUE TITLE
受注編集からの加算ポイントに上限が無い

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/point-plugin#82]
## 現象

受注編集からの加算ポイント入力に、加算ポイントには上限がありませんでした。
## 再現手順

1．受注マスタから検索する
2．受注を選択する
3．確定ステータスに変更して加算ポイントに1億を入力する
　=>入力出来ていて、保留ポイントは1億になってしまいました（ＮＧ）
## 期待値

加算ポイントは100,000ptが上限であること。

**Comment by chihiro-adachi** [comment]
intの上限(~~8桁~~9桁)のチェックを行う
(運用上は、お支払い金額の範囲内が望ましい)

**Comment by lammn** [comment]
今は、9ケタまで入力出来ます。
`値が長すぎます。9文字以内でなければなりません。`

**Comment by chihiro-adachi** [comment]
誤：8桁
正：9桁

でした。現状の動作で問題ありません。
