### ISSUE TITLE
カート画面でマイナスポイントが表示されている

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/point-plugin#85]
## 現象

保有ポイントがマイナスのとき、
カート画面でマイナスポイントが表示されています。
![image](https://cloud.githubusercontent.com/assets/16891862/15312964/e9d5d452-1c42-11e6-8893-858d672e959b.png)
## 再現手順

1.保有ポイントがマイナスポイントの状態にする。
　⇒手順はhttps://github.com/EC-CUBE/point-plugin/issues/79
2.カート画面に行く。
　⇒マイナスポイントが表示されている（NG）
## 期待値

マイナスポイントの場合、「0」を表示すること。

**Comment by chihiro-adachi** [comment]
以下で修正されているため、クローズします。
https://github.com/EC-CUBE/point-plugin/commit/c28412523fb62c359795810b005b2e35e0f08b66
