### ISSUE TITLE
注文でマイナスポイント発生時に、エラーが重複して表示される

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/point-plugin#86]
## 現象

注文でマイナスポイント発生時に、購入完了画面にエラーを表示しますが、
エラーが重複して２つ表示されています。
![image](https://cloud.githubusercontent.com/assets/16891862/15313132/30f726e6-1c44-11e6-9cb3-a93e20e3804e.png)
## 再現手順

1.保有ポイントがマイナスになる注文を行う。
　⇒手順は#79
　⇒エラーが重複して表示されている（NG）
## 期待値

エラーは１つだけ表示されること。

**Comment by chihiro-adachi** [comment]
#129 で対応
