### ISSUE TITLE
購入フローで値引き金額がマイナスの場合、利用ポイントを利用しても反映されない

### ISSUE THREAD

**Issue by geany-y** [EC-CUBE/point-plugin#90]
## 現象

ご注文情報の確認画面で利用ポイントを使用しているにも関わらず、
利用ポイント表示が「0」ポイントになる
## 再現手順

①購入フローでご注文情報の確認まで遷移
②「dtb_order」の「discount」にマイナス値を設定
③利用ポイント画面で、保有ポイント内でポイント利用
④ご注文情報の確認画面に遷移する
## 期待値

①ポイント利用時にメッセージを表示

**Comment by nanasess** [comment]
#80 にて修正しています

**Comment by chihiro-adachi** [comment]
#80 と重複のため、クローズします。
