### ISSUE TITLE
負の整数から正の整数への変換

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/point-plugin#91]
負の整数を正の整数に変換する場合、以下の3パターンが使用されている
- `-($minus_integer)`
- `$minus_integer * -1`
- `abs($minus_integer)`

`$minus_integer` がコード上からは正の整数か、負の整数かを判断しづらく、可読性が落ちるため、必ず負の整数が代入されているケースの場合は、 `abs($minus_integer)` を使用するべき。

**Comment by chihiro-adachi** [comment]
明らかに判断が着く箇所は修正を行う

**Comment by chihiro-adachi** [comment]
#91 で対応
