### ISSUE TITLE
Application インスタンスの生成でデッドロックの懸念

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/point-plugin#98]
多くのクラスのコンストラクタで `$this->app = \Eccube\Application::getInstance();` をコールしているが、稀にデッドロックを誘発するため、使用は最小限にした方が良い

**Comment by chihiro-adachi** [comment]
Eventの実行クラス以外の箇所は、引数で渡ってくるApplicationインスタンスへ置き換える
